# Debug path variables
# previz
DEBUGFILE_PREVIZ_CHR='Z:/06_PARTAGE/DEBUG_FILES/BATCHATOR/Previz_CHR_Release_debug.txt'
DEBUGFILE_PREVIZ_PRP='Z:/06_PARTAGE/DEBUG_FILES/BATCHATOR/Previz_PRP_Release_debug.txt'
DEBUGFILE_PREVIZ_SET='Z:/06_PARTAGE/DEBUG_FILES/BATCHATOR/Previz_SET_Release_debug.txt'
#modeling
DEBUGFILE_MODELING_CHR='Z:/06_PARTAGE/DEBUG_FILES/BATCHATOR/Modeling_CHR_Release_debug.txt'
DEBUGFILE_MODELING_PRP='Z:/06_PARTAGE/DEBUG_FILES/BATCHATOR/Modeling_PRP_Release_debug.txt'
DEBUGFILE_MODELING_SET='Z:/06_PARTAGE/DEBUG_FILES/BATCHATOR/Modeling_SET_Release_debug.txt'
# render
DEBUGFILE_RENDER_CHR='Z:/06_PARTAGE/DEBUG_FILES/BATCHATOR/Render_CHR_Release_debug.txt'
DEBUGFILE_RENDER_PRP='Z:/06_PARTAGE/DEBUG_FILES/BATCHATOR/Render_PRP_Release_debug.txt'
DEBUGFILE_RENDER_SET='Z:/06_PARTAGE/DEBUG_FILES/BATCHATOR/Render_SET_Release_debug.txt'
# anim
DEBUGFILE_ANIM_CHR='Z:/06_PARTAGE/DEBUG_FILES/BATCHATOR/Anim_CHR_Release_debug.txt'
DEBUGFILE_ANIM_PRP='Z:/06_PARTAGE/DEBUG_FILES/BATCHATOR/Anim_PRP_Release_debug.txt'
DEBUGFILE_ANIM_SET='Z:/06_PARTAGE/DEBUG_FILES/BATCHATOR/Anim_SET_Release_debug.txt'


# GUI
Z2K_ICONPATH = "zombie/python/dminutes/Z2K_ReleaseTool/icons/Z2K_ReleaseTool/"
