

global proc
AEBE_VDBSwitchTemplate( string $nodeAttr )
{
    editorTemplate -beginScrollLayout;
    {

            editorTemplate -beginLayout "BE_VDBSwitch" -collapse 0;
            editorTemplate -beginNoOptimize;
            {
              editorTemplate -addControl "SelectInput";

            }
        editorTemplate -endNoOptimize;
        editorTemplate -endLayout;
        editorTemplate -addExtraControls;
		
    }
    editorTemplate -endScrollLayout;
}



